name: status_saver
description: Simple whatsapp saver


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  image_gallery_saver: ^1.7.1
  video_player: ^2.4.7
  chewie: ^1.3.5
  provider: ^6.0.3
  share_plus: ^4.1.0
  flutter_native_api: ^0.0.1
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  
